// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using simulator_back_end.Data;

namespace simulator_back_end.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190610142539_FirstMigrations")]
    partial class FirstMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("simulator_back_end.Models.SimCab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Data");

                    b.Property<decimal>("Juros");

                    b.Property<string>("Titulo");

                    b.Property<int>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SimCabs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Data = "10/06/2019",
                            Juros = 4.12m,
                            Titulo = "Fiat Uno Vivace",
                            UsuarioId = 1
                        });
                });

            modelBuilder.Entity("simulator_back_end.Models.SimDet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Parcela");

                    b.Property<int>("SimCabId");

                    b.Property<decimal>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("SimCabId");

                    b.ToTable("SimDets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Parcela = 1,
                            SimCabId = 1,
                            Valor = 8234.12m
                        },
                        new
                        {
                            Id = 2,
                            Parcela = 2,
                            SimCabId = 1,
                            Valor = 8234.12m
                        },
                        new
                        {
                            Id = 3,
                            Parcela = 3,
                            SimCabId = 1,
                            Valor = 8234.12m
                        });
                });

            modelBuilder.Entity("simulator_back_end.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Senha")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "abc@abc.com",
                            Senha = "123"
                        });
                });

            modelBuilder.Entity("simulator_back_end.Models.SimCab", b =>
                {
                    b.HasOne("simulator_back_end.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("simulator_back_end.Models.SimDet", b =>
                {
                    b.HasOne("simulator_back_end.Models.SimCab", "SimCab")
                        .WithMany()
                        .HasForeignKey("SimCabId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
